load_module modules/ngx_http_js_module.so;

worker_processes auto;
error_log stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    js_path /etc/nginx/njs;
    js_import render from examples/basic/render.njs;

    server {
        listen 8080;
        server_name _;

        location = / {
            js_content render.handle;
        }
    }
}
